#!/bin/bash

# Text editor
alias txx='~/dev/text-editor/build/txx'
alias txx2='~/dev/text-editor-2/build/txx'
alias ntxx='~/dev/ntxx/build/ntxx'

alias vi='nvim'
alias vim='nvim'

alias explorer="explorer.exe ."

alias py='python3'


function cclip ()
{
    if [ -n "$1" -a -n "$2" -a ! -n "$3" ]; then
        if [ "$2" != "-d" ]; then
            echo "Invalid flag"
            echo "Usage: cclip <file_name>"
            echo "Flags: -d <discord_mode>"
            return 0
        fi

        file_content=$(cat "$1")
        prefix="${1##*.}"
        modified_text=$'```'"$prefix"$'\n'"$file_content"$'```'
        printf "%s" "$modified_text" | xclip -selection clipboard

    elif [ -n "$1" -a ! -n "$3" ]; then
        xclip "$1" -selection clipboard
    else
        echo "Usage: cclip <file_name>"
        echo "Flags: -d <discord_mode>"
    fi

}


function cmkdir ()
{
    if [ -n "$1" ]; then
        mkdir "$1" && cd "$1"
    else
        echo "Usage: cmkdir <directory_name>"
    fi
}

# nvm bullshit
export NVM_DIR="/home/lucas/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
. "$HOME/.cargo/env"
